import type { TransactionCategory } from "@/types/transaction.types";

const categoryMap: Record<TransactionCategory, string[]> = {
    Food: [
        "food",
        "rice",
        "groceries",
        "restaurant",
        "pizza",
        "burger",
        "beans",
        "garri",
        "yam",
        "snacks",
        "egg",
        "burger",
        "restaurant",
        "chicken",
        "meat",
        "fish",
        "suya",
        "pizza",
        "bread",
        "groundnut",
        "eba",
        "water",
        "pure water",
        "bottle water",
        "drink",
        "coke",
        "pepsi",
        "juice",
        "gala",
        "biscuit",
        "parfait",
        "ice cream",
    ],
    Bills: [
        "airtime",
        "data",
        "electricity",
        "wifi",
        "subscription",
        "netflix",
        "rent",
        "fuel",
        "dstv",
        "gotv",
        "netflix",
        "recharge",
        "gas",
        "waste",
        "tax",
        "debt",
    ],
    Transport: [
        "uber",
        "taxi",
        "bus",
        "transport",
        "car",
        "bike",
        "bolt",
        "danfo",
        "okada",
        "brt",
        "keke",
        "fare",
        "delivery",
        "waybill",
        "logistics",
    ],
    Income: [
        "salary",
        "freelance",
        "hustle",
        "crypto",
        "p2p",
        "refund",
        "gift",
        "bonus",
        "transfer",
        "ällowance",
    ],
    Entertainment: [
        "movies",
        "game",
        "cinema",
        "pubg",
        "cod",
        "playstation",
        "club",
        "hangout",
        "concert",
        "ticket",
        "spotify",
        "apple music",
        "youtube"
    ],
    Health: [
        "medicine",
        "drug",
        "clinic",
        "hospital",
        "phamarcy",
        "checkup",
        "dentist",
        "fitness",
        "gym"
    ],
    Education:[
        "book",
        "courses",
        "school",
        "fees",
        "handout",
        "udemy",
        "exam",
        "jamb",
        "waec",
        "stationary",
        "pdf",
        "pen"
    ],
    Shopping: [
        "bags",
        "clothes",
        "shirt",
        "short",
        "trouser",
        "underwear",
        "shoes",
        "shopping",
        "generator",
        "fan",
        "perfume",
        "lotion",
        "soap",
        "cream",
        "haircut",
        "barber",
        "salon",
        "watch",
        "sneakers",
        "cap",
    ],
    Appliances: [
        "fan",
        "generator",
        "bed",
        "iron",
        "bulb",
        "extensions",
        "socket",
        "fridge",
        "ac",
        "television",
        "tv",
        "microwave",
        "blender",
        "cooker"
    ],
    Gadgets: [
        "phone",
        "laptop",
        "charger",
        "earpiece",
        "earbuds",
        "headphone",
        "powerbank",
        "pouch",
        "screenguards",
        "camera",
        "keyboard",
        "mouse",
        "watch",
        "console",
        "ps4",
        "ps5",
        "xbox",
        "monitor",
        "ipad",
        "tablet",
        "drive",
        "ssd",
        "hub",
        "cable"
    ],
    Other: [],
}

export function detectCategory(input: string) : TransactionCategory {
    const lowerInput = input.toLowerCase();

    for (const category in categoryMap) {
        const keywords = categoryMap[
            category as TransactionCategory
        ];

        const matched = keywords.some((keyword) => 
            lowerInput.includes(keyword)
        );

        if(matched){
            return category as TransactionCategory;
        }
    }

    return "Other";
}